added result and answers page
pankaj-prog/quiz-app pull request #3
Opened 2022-02-20 15:23 UTC by pankaj-prog

Score / Result Page
![Quiz app - result](https://user-images.githubusercontent.com/82706396/154850000-9e03ad48-3b96-4a6d-904d-06c7ece58999.png)

Answers Page
![Quiz app - answers](https://user-images.githubusercontent.com/82706396/154850003-2203bf34-1776-4787-a580-7128fe1dbc5e.png)

2022-02-20 15:40 UTC, j24m approved these changes
Hey, your code looks good, did not see anything to be changed except at one place you used a property twice, I like your UI too. Good work there, keep it up. :)

2022-02-20 15:40 UTC, j24m commented on common.css
> +  justify-content: space-between;
here you have accidentally given the same property twice.

2022-02-20 15:54 UTC, manojsarna requested changes
UI Review :

-- Black and white theme looks good!! , but the border you have used in options is not looking that great , you can change it.
 
-- Alignment of Rules Page

-- Can Add Score in Questions Page

2022-02-20 15:54 UTC, manojsarna commented on src/pages/answers/answers.css
> +  border: none;
good work!! 

Suggestion : can add prefix eg var(--COLOR-ERROR). While accessing the colors in a new variable , you can access the list of the colors just by Ctrl + Space. So keep that in mind!!

2022-02-20 15:54 UTC, manojsarna commented on src/pages/answers/answers.html
> +  </body>
Try to give the link of your REPO instead of your user profile!!

it will be easier for Reviewers to find your repo!! :)

2022-02-20 15:54 UTC, manojsarna commented on src/pages/rules/rules.html
> +  </body>
Check Here Too , for github link!!

2022-02-20 15:54 UTC, manojsarna commented on src/pages/rules/rules.html
> +        </ol>
Good you are using semantic HTML :)

2022-02-20 15:54 UTC, manojsarna commented on src/pages/rules/rules.css
> +  font-size: large;
Suggestion : can use rems!!

2022-02-20 15:54 UTC, manojsarna commented on src/pages/result/result.html
> +</html>
Check Here Too , for github link!!

2022-02-20 15:54 UTC, manojsarna commented on src/pages/result/result.css
> +}
check for color varibale naming !!

2022-02-20 15:54 UTC, manojsarna commented on src/pages/questions/questions.html
> +</html>
check this for github repo link!!

2022-02-20 16:19 UTC, gauravsinhaweb approved these changes
Looks good to me. Good to merge

2022-02-20 16:19 UTC, gauravsinhaweb commented on src/pages/answers/answers.html
> +            Q.1 Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi,
minor change: use list tag for listing question and option.

2022-02-20 16:20 UTC, pankaj-prog commented on common.css
> +  justify-content: space-between;
i will remove one.
Thankyou for mentioning it

2022-02-20 16:20 UTC, pankaj-prog commented on src/pages/answers/answers.css
> +  border: none;
okay

2022-02-20 16:20 UTC, pankaj-prog commented on src/pages/answers/answers.html
> +  </body>
yeah will update it

2022-02-20 16:24 UTC, pankaj-prog commented on src/pages/rules/rules.html
> +        </ol>
Thanks

2022-02-20 16:26 UTC, pankaj-prog commented on src/pages/answers/answers.html
> +            Q.1 Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi,
okay

2022-02-20 19:23 UTC, merged

2022-02-21 16:39 UTC, tarunsankhla reviewed
Overall the code is consistent, only minor changes

2022-02-21 16:39 UTC, tarunsankhla commented on src/pages/result/result.css
> +  gap: 8px;
gap would be better in rem based on screen size to maintain flow of spaces

2022-02-21 16:39 UTC, tarunsankhla commented on src/pages/questions/questions.html
> +      <div class="question-wrapper">
can you add comments in you html code

2022-02-21 16:39 UTC, tarunsankhla commented on src/pages/rules/rules.html
> +</html>
Overall you have used semantic html and classNames are also correct, only minor changes I have commented

2022-02-21 16:39 UTC, tarunsankhla commented on common.css
>    max-width: 1000px;
can use rems instead of px

2022-02-21 16:39 UTC, tarunsankhla commented on src/pages/result/result.css
> +  min-width: 300px;
try using rem here too

2022-02-21 16:43 UTC, tarunsankhla reviewed
only Minor changes good to merge

2022-02-21 16:43 UTC, tarunsankhla commented on src/pages/answers/answers.html
> +          </p>
try using UL and LI list tags for this